

{{- if .Values.envSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envSecret.name }}
  labels:
    app.kubernetes.io/name: {{ include "quay-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  API_TOKEN: {{ .Values.envSecret.token | quote }}
{{- end }}